### PR TITLE
Fix doc issue.

### PR DESCRIPTION
**Pull request by toyboxman**
dsl-guide describes two kinds of rules, Uniqueness and Distinctness. actually they are similiar rule, so we merely keep Uniqueness rule.

### CODE REVIEW

**Comment by toyboxman** [comment]
Sure, I'll update this PR and keep Distinctness instead of Uniqueness

**Comment by guoyuepeng** [comment]
I don't know either.

**Comment by toyboxman** [comment]
retry again, it's fine.

Thanks guys

**Comment by bhlx3lyx7** [comment]
Thanks @toyboxman , we can merge this PR.

**Pull request closed without merging**
