### PR TITLE
Doc/enhancement

### PR DESCRIPTION
**Pull request by younglee1**
update some documents

### CODE REVIEW

**Comment by guoyuepeng** [comment]
Hi Lee,

Thanks for making our document great.

William

**Comment by bhlx3lyx7** [comment]
Hi @younglee1 , thanks for your work.
I've reviewed the modifications you've made, and have some suggestions:
1. In `griffin-doc/deploy/deploy-guide.md`, "For Griffin users, please follow the instructions below to you can deploy Griffin in your environment" confused me.
2. In `griffin-doc/docker/griffin-docker-guide.md`, "There are four pre-built griffin environment images", actually, only the first one is the griffin docker image, the next two are re-built based on the official images, the last one is the official image of zookeeper, so I don't think we can say they are four pre-built images, we'd better say it like "Here liststhe griffin and dependent environment docker images".

Would you mind make some changes? We'll accept after that.

**Comment by younglee1** [comment]
Hi @bhlx3lyx7 , 
I made some small changes according to your suggestions. Please take a look.

**Comment by bhlx3lyx7** [comment]
Cool, it seems good, we'll merge it. Thanks @younglee1  for your work~

**Pull request closed without merging**
