### PR TITLE
Initialize base metric model

### PR DESCRIPTION
**Pull request by toyboxman**
Propose a basic and elementary metric model definition.

### CODE REVIEW

**Comment by toyboxman** [comment]
@guoyuepeng , Can you review my update on your change?

**Comment by guoyuepeng** [comment]
> @guoyuepeng , Can you review my update on your change?

when users want to publish metric value, we might also attach tags in the coming metric value?
should we update this part in metricv?

**Comment by toyboxman** [comment]
> > @guoyuepeng , Can you review my update on your change?
> 
> when users want to publish metric value, we might also attach tags in the coming metric value? should we update this part in metricv?

Good point.
@guoyuepeng I have added tag property into metricV entity, and complemented java doc.

**Comment by guoyuepeng** [comment]
LGTM, merged to griffin-2.0.0-dev.

**Pull request merged**
