### PR TITLE
[GRIFFIN-195] Don't list all tables from UI

### PR DESCRIPTION
**Pull request by chemikadze**
[GRIFFIN-195]
Initially, load only list of databases and list of table names.
Table information is loaded only if user clicks on specific table.

[GRIFFIN-196]
Search by table names.

### CODE REVIEW

**Comment by bhlx3lyx7** [comment]
I've tested this PR, the filtering feature works good, but only in profiling creation step. Would you add it in accuracy creation steps as well?

**Comment by chemikadze** [comment]
@bhlx3lyx7 my thoughts exactly, will push in a few minutes

**Comment by chemikadze** [comment]
@bhlx3lyx7 pushed the same for accuracy

**Comment by bhlx3lyx7** [comment]
Cool, seems good to me, I can merge it now.

**Pull request closed without merging**
