### PR TITLE
GRIFFIN-164 GRIFFIN-186 GRIFFIN-187: Profiling Re-factor + Regex/Empty String Support

### PR DESCRIPTION
**Pull request by spencer-hivert-ck**
We've been working away on Griffin here at Credit Karma, and we'd love to contribute back!

This PR tackles three separate tasks:

- [GRIFFIN-164](https://issues.apache.org/jira/browse/GRIFFIN-164): Regex Support
- [GRIFFIN-186](https://issues.apache.org/jira/browse/GRIFFIN-186): Create Profiling Measure Re-Factor
- [GRIFFIN-187](https://issues.apache.org/jira/browse/GRIFFIN-187): Empty String Support

The details for each of these tasks can be found in the JIRA tickets linked above!

### CODE REVIEW

**Comment by bhlx3lyx7** [comment]
I've reviewed the code for GRIFFIN-164, which seems good.

**Comment by icesmartjuan** [comment]
Test from UI based on your current measure and service :
1. create Accuracy and Publish measure successfully
2. fail to create Data Profiling measure
pr.component.ts: line 390 fails the Profiling and Publish measure creation, as this.step3.size is undefined type
3. failed to create job with above created Accuracy measure
{"timestamp":1533207681903,"status":400,"error":"Bad Request","code":"40011","message":"We don't support such measure type.","path":"/api/v1/jobs"}
```this.newJob
{job.name: "job1", job.type: "batch", measure.id: 1, cron.expression: "0 0/4 * * * ?", cron.time.zone: "GMT-8:00", …}cron.expression: "0 0/4 * * * ?"cron.time.zone: "GMT-8:00"data.segments: Array(2)0: as.baseline: truedata.connector.name: "source1533207565052"segment.range: begin: "-1day"length: "1day"__proto__: Object__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ ()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()1: data.connector.name: "target1533207568926"segment.range: begin: "-1day"length: "1day"__proto__: Object__proto__: Objectlength: 2__proto__: Array(0)job.name: "job1"job.type: "batch"measure.id: 1__proto__: Object```

**Comment by spencer-hivert-ck** [comment]
Thanks for taking a look at my PR @icesmartjuan!

I'm unable to re-produce any of the errors you've mentioned above. Regarding #2, I've added default values to the fields in step 3, so that error should not occur. Regarding #3, I didn't change the accuracy or job code, so that error may be unrelated.

I brought up a fresh version of the service/ui and was unable to re-produce the failures described above. Are you able to provide more detailed steps and/or photos so I can attempt to re-produce these errors myself!

Thank you.

**Comment by icesmartjuan** [comment]
tested with newly commit, create Profiling measure successfully, create jobs with the Profiling measure sucessfully

**Pull request closed without merging**
